name: Deploy to GitHub Pages

on:
  push:
    branches:
      - ["main"]   # or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: engine   # path to your folder containing index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
